theme: jekyll-theme-time-machine
title: Aiden Quinlan's Page
description: Welcome to my page! Here you can find my resume, projects, and experience that any potiential employers and collaborators may find interesting.
